CYB-16
tp47/cybreach pull request #15
Opened 2023-11-21 10:12 UTC by mrzenxxx

Задача: 
https://linear.app/cybreach/issue/CYB-16/realizovat-logiku-avtorizacii

Реализация: 
1) Класс AuthApi с методами регистрации, логина, логаута, получения данных пользователя, изменения данных пользователя.
2) Контекст с данными пользователя и функцией изменения данных из любой части приложения
3) Компоненты высшего порядка для публичных и приватных роутов, перенастроен роутер

Имеется глюк из-за асинхронности получения данных и setState, в результате чего при валидных данных для входа нас перенаправляет обратно с главной страницы на страницу логина, то есть мы вводим логин и пароль, но когда реакт рендерит страницу, он еще не получил данные пользователя и не установил в стейт, поэтому не открывает доступ к роуту. При обновлении страницы он уже делает всё, почти как надо (страница логина мелькает на доли секунды и затем рисуется Main). 
**Прошу вас подсказать, что можно с этим сделать.**

2023-11-22 10:41 UTC, KataevAS requested changes

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/App.tsx
> +      .then(() => setIsAuth(true))
А для чего тут цепочка .then? В предыдущем же нету ничего асинхронного

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/hocs/AnonimousRoute/AnonimousRoute.tsx
> +const AnonimousRoute: React.FC<AnonimousRouteProps> = ({ page }) => {
Предложу отрефакторить компонент таким образом:
![image](https://github.com/tp47/cybreach/assets/38090158/a70d0a9c-497a-4f4c-8b77-2bae717ff799)

1. Нет необходимости явно указывать что сам компонент AnonimousRoute является FC, это устаревшая тема.
2. Пропс page лучше явно указать как JSX.Element, т.к. строку, например, оборачивать в такой hoc не вижу никакой необходимости. (+так можно избавиться от лишней обертки ReactFragment)
3. Использовать useNavigate согласное рекомендации авторов библиотеки
![image](https://github.com/tp47/cybreach/assets/38090158/7c004bc2-8f3f-4b80-8b0d-5a05b0affa00)

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/hocs/ProtectedRoute/ProtectedRoute.tsx
> +const ProtectedRoute: React.FC<ProtectedRouteProps> = ({ page }) => {
Аналогично комменту выше

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +      .then(() => setUser())
снова не очень понятная цепочка вызовов

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/organisms/RegisterForm/RegisterForm.tsx
> +      .then(() => setUser())
тоже поправить цепочку вызовов

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/LoginPage/LoginPage.tsx
> +    <main className="h-screen bg-custom-layout flex mx-auto justify-center items-center">
Лучше использовать Layout из папки templates

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/Profile.tsx
> +      .then(() => setIsAuth(false))
цепочка вызовов

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/Profile.tsx
> +        <div className="flex justify-center align-center flex-col items-center h-[100%]">
Для height: 100% есть отдельный класс h-full

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/Profile.tsx
> +              {JSON.stringify(currentUser, null, 2)}
Это не тестовое осталось?

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/Profile.tsx
> +            className="
Если стилизация не отличается от дефолтной, то не нужно переопределять тут

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/pages/RegisterPage/RegisterPage.tsx
> +      <main className="h-screen bg-custom-layout flex mx-auto justify-center items-center">
Layout из папки templates

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/services/api/authApi.ts
> +        return (await res.json()) as T
если есть .json() то уже нужно обернуть в try catch. Так же стоит подумать как организовать отлов ошибок в классе для всех запросов.

2023-11-22 10:41 UTC, KataevAS commented on packages/client/src/components/App.tsx
> +    AuthApi.getUser()
По идее, если это инициализационный запрос, то нужен какой-то пендинг, для блока отрисовки остальных компонентов при первом рендере, до окончания загрузки инициализации, т.к. это лишние действия.

2023-11-22 11:45 UTC, mrzenxxx commented on packages/client/src/components/pages/Profile.tsx
> +              {JSON.stringify(currentUser, null, 2)}
Здесь я вывел объект на экран и оставил для наглядности, что все данные получаются и сохраняются в стейт корректно,  в дальнейшем (после того как сверстаем страницу профиля), из этой переменной будут заполняться поля.

2023-11-22 13:45 UTC, mrzenxxx commented on packages/client/src/components/hocs/AnonimousRoute/AnonimousRoute.tsx
> +const AnonimousRoute: React.FC<AnonimousRouteProps> = ({ page }) => {
По этому замечанию: мне нравится предложенный вариант, но получилось его применить лишь частично. 
В публичных роутах (Anonimous) - всё чётко работает, переписал полностью.

В приватных роутах(Protected) замечен вот такой эффект: если переписать компонент, как ты предлагаешь, то теряется реактивность - не до конца понимаю где и почему, но факт - можно из адресной строки запустить переход на страницу "/" и в этом случае приложение заново инициализируется и стейт слетает. У нас проверка пользователя происходит единожды по запросу - при инициализации App. Так вот, почему-то после этого запроса и обновления стейта, компонент не обновляется и мы остаёмся на странице Main, дальше уже при переходе на страницы нас выкидывает на форму.
Оставляю пока эти компоненты в разной реализации, хотелось бы от ревьювера Практикума получить комментарий по этому вопросу.

2023-11-22 13:46 UTC, mrzenxxx commented on packages/client/src/components/App.tsx
> +      .then(() => setIsAuth(true))
Я убрал это везде, согласен что неправильно.

2023-11-23 05:10 UTC, KataevAS commented on packages/client/src/components/hocs/AnonimousRoute/AnonimousRoute.tsx
> +const AnonimousRoute: React.FC<AnonimousRouteProps> = ({ page }) => {
@mrzenxxx тогда может так?
<img width="532" alt="image" src="https://github.com/tp47/cybreach/assets/38090158/5981b2de-26c1-44d9-8104-0c46b847f5d2">
<img width="533" alt="image" src="https://github.com/tp47/cybreach/assets/38090158/bfe8f436-b599-4f7b-805e-26be67053437">

2023-11-23 05:21 UTC, KataevAS requested changes
Попробуй, когда ты авторизован, зайти по ссылке http://localhost:3000/profile на страницу профиля (т.е. не в рамках SPA, а первый раз зайти по этой ссылке)

2023-11-23 05:21 UTC, KataevAS commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +        setUser()
Внутри асинхронный запрос, что будет, если запрос loginUser выполнился успешно, а данные в getUser получить не удалось?

2023-11-23 05:21 UTC, KataevAS commented on packages/client/src/components/organisms/RegisterForm/RegisterForm.tsx
> +        setUser()
Вопрос как и в LoginForm

2023-11-23 13:04 UTC, tp47 approved these changes

2023-11-23 21:55 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать

Хорошего дня :)

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/components/App.tsx
> +    AuthApi.getUser()
В дальнейшем предлагаю вынести на уровень redux-thunk или любого другого менеджера состояний (рекомендация) 

Предлагаю также использовать async / await для работы с промиссами, так код будет более читаемым (рекомендация) 
https://learn.javascript.ru/async-await

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/components/App.tsx
> +  return isAuth === null ? (
Не очень красивая запись получается с тернарником

Предлагаю следующее:
```
if (isAuth == null) {
  return <MainLayout content={<LoaderStub />} />
}

return (
  JSX
)
```

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/components/atoms/Button/Button.tsx
> +    bg-green-950
Такое ощущение, что классы съехали

Обычно это резолвит линтер, но тут видимо это не учитывается

Предлагаю сместить на два таба вправо, что запись имела следующий вид:
```
className="
  bg-green-950
  ...
```

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/components/organisms/RegisterForm/RegisterForm.tsx
> +        <Button label="HAVE ACCESS? BREACH IN!" type="button" onClick={() => navigate('/signin')} />
Предлагаю вынести в функцию в теле компоненты

Прокидывать инлайн колбеки можно, но это сложнее оптимизировать и читать

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/components/pages/Profile.tsx
> +// import { useNavigate } from 'react-router-dom'
Если не используется - удаляем
YAGNI - https://web-creator.ru/articles/yagni

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/services/api/authApi.ts
> +    return fetch(`${this._baseUrl}/auth/signup`, {
Для работы с запросами предлагаю следующее:
Добавить в проект библиотеку axios: https://www.npmjs.com/package/axios
Далее сконфигурировать один экземпляр, где будут установлены все необходимые настройки по умолчанию: https://axios-http.com/ru/docs/instance

И уже этот экземпляр использовать для запросов
Это будет что-то следующее:
```
const instance = axios.create({
  baseURL: BASE_URL,
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});

async createUser(user: User) {
  try {
    const response = instance.post<User>('user/create', user)
    return response
  } catch (error) {
    // handle error
  }
```

2023-11-23 21:55 UTC, IvanPeleshok commented on packages/client/src/services/context/userContext.ts
> +  // eslint-disable-next-line
Предлагаю не игнорировать линтер

2023-11-24 07:19 UTC, mrzenxxx commented on packages/client/src/components/App.tsx
> +  return isAuth === null ? (
"Не очень красиво" - это субъективно всё же - у каждого своё чувство прекрасного. 
Я выбрал вариант записи с тернарником не из-за красоты, просто ранее, в рамках выполнения данного задания, переписывал компоненты AnonimousRoute/ProtectedRoute по замечаниям коллеги (можно найти в истории комментариев к ПР), и столкнулся с нежелательным поведением - а именно потерей реактивности при записи через условный рендеринг (с использованием if). Поэтому для себя сделал вывод, что весь рендеринг лучше делать в рамках одного return. Поправьте, если ошибаюсь.
Сейчас я исправил свой код по Вашей рекомендации и всё работает корректно, но всё же я не понимаю, от чего эта корректность зависит и как это прогнозировать.

2023-11-24 07:48 UTC, mrzenxxx commented on packages/client/src/components/App.tsx
> +    AuthApi.getUser()
Да, у нас это в планах, но выходит за рамки материалов спринта, поэтому пока эта реализация - условно, временная.

2023-11-24 10:51 UTC, mrzenxxx commented on packages/client/src/services/api/authApi.ts
> +    return fetch(`${this._baseUrl}/auth/signup`, {
Понял Вашу идею, но устанавливать дополнительную библиотеку в рамках данного задания считаю избыточным, т.к. в дальнейшем от неё все равно придётся избавиться - мы будем использовать для запросов RTKQuery, а сейчас это выходит за рамки спринта.
Но я всё же отрефакторил класс: без библиотеки, но с заимствованием концепции, и код стал чище.
PS. catch в методах класса не используется, т.к. обработка ошибок происходит в методе _getResponse.

2023-11-24 11:09 UTC, mrzenxxx commented
Добрый день, Иван! Замечания исправлены и я оставил свои комментарии.

2023-11-24 21:02 UTC, IvanPeleshok commented on packages/client/src/components/App.tsx
> +  return isAuth === null ? (
Предлагаю обратиться к вашему наставнику с этим вопросом и разобрать кейс, когда у вас не работало по той логике, которая вам казалась рабочей

Реакт по реализации не имеет никого отношения к реактивности, это планировщик, который может приоритизировать выполнение команд по внутренним механизмам
Предлагаю посмотреть следующие темы про реакт для более глубоко понимания:
https://www.youtube.com/watch?v=A0W2n2azH5s

Все "реактивности" реализуются с помощью сеттеров, будь то классовый или функциональный компонент

Как пример, разберём пример с хуков useState:

```
const Component: FC<Props> => (props) = {
  const [state, setState] = useState<IState>({ property: 'value' })
  
  const onClick = (event: React.MouseEvent<HTMDivElement>) => {
    state.property = 'newValue'  // не произойдёт ререндера компоненты, т.к мы меняем значение напрямую и реакт не триггерит перерисовку
  
    setState({ property: 'newValue }) // обновляем состояние значения state и вызываем ререндер компонента
  }
  
  return (
    <button onClick={onClick} />
}
```

2023-11-24 21:08 UTC, IvanPeleshok commented on packages/client/src/services/api/authApi.ts
> +    return fetch(`${this._baseUrl}/auth/signup`, {
Замечательно, что пишите свои обёртки для работы с запросами

Уверен, что при переходе на готовое решение от RTKQuery или любое другое у вас всё будет отлично с реализацией, чувствуется вдумчивый подход

Я лишь показал как обычно работают с апи в большинстве случае с использованием axios: пакет легковесный и имеет огромный охват среди разработчиков на js

2023-11-24 21:10 UTC, IvanPeleshok approved these changes
Всё замечательно, работа не имеет критических замечаний

Поздравляю, работа принята!

Хорошего дня :)

С удовольствием посмотрю на ваш результат в дальнейшем 🚀

2023-11-25 00:41 UTC, merged