Create hook useAuth
tp47/cybreach pull request #18
Opened 2023-11-29 12:41 UTC by Kaitag7

Задача по разработке хука для авторизации
https://linear.app/cybreach/issue/CYB-33/razrabotat-i-podklyuchit-hookhoc-dlya-avtorizacii

2023-11-29 13:30 UTC, Memento-mo requested changes

2023-11-29 13:49 UTC, Kaitag7 commented on packages/client/src/components/App.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
при передаче getuser в массив зависимостей, аппа уходит в бесконечный цикл, поэтому и убрал, а прежде чем закомментить линтер, поискал другие варианты, но не нашел, если есть что предложить вместо этого, предложи пожалуйста

2023-11-29 13:51 UTC, Memento-mo commented on packages/client/src/components/App.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
есть setCurrentUser(data)
можешь добавить в самое начало проверку if (currentUser) return, он первый раз сделает запрос, и в цикл не уйдет, т.к юзер уже существует

2023-11-29 14:10 UTC, Kaitag7 commented on packages/client/src/components/App.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
ага в useEffect, да такой вариант подходит, спасибо, только еще в проверку докину isAuth, так как он после первого рендера становится true
if (currentUser && isAuth) return

2023-11-29 15:11 UTC, Memento-mo approved these changes

2023-11-29 19:14 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-11-29 19:14 UTC, IvanPeleshok commented on packages/client/src/hooks/useAuth.ts
> +  const getUser = () => AuthApi.getUser()
Предлагаю обернуть каждую функцию в useCallback
https://habr.com/ru/companies/otus/articles/696610/#:~:text=%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D0%B5%D1%82%20%D1%85%D1%83%D0%BA%20useCallback.-,useCallback,-useCallback%20%D0%BF%D0%BE%D0%B4%20%D0%BA%D0%B0%D0%BF%D0%BE%D1%82%D0%BE%D0%BC

В случае ререндера функция будет пересоздаваться только при изменении зависимостей в массиве вторым аргументом хука useCallback

P.S: С контекстом необходимо аккуратно работать, т.к он провоцирует перерисовку дочерних компонентов

Иногда лучшее решение использовать стандартные решения от redux-thunk / effector / mobx и т.д для работы с получением данных и их отправкой

2023-11-29 20:02 UTC, Kaitag7 commented on packages/client/src/hooks/useAuth.ts
> +  const getUser = () => AuthApi.getUser()
Добавил useCallback на все функции. По поводу комментария по сторе вместо контекста, сейчас у нас есть задачка по переводу работы с получением данных и их отправкой через редакс, которая в процессе разработки.

2023-11-30 16:40 UTC, IvanPeleshok approved these changes
Хорошая работа!

Апрув

2023-12-12 16:45 UTC, Kaitag7 commented
В проекте стали использовать более стандартное решение в виде хранилища состояния redux, в связи с чем надобность использования данного хука пропала, поэтому эту ветку в проект вливать не стал.

2023-12-12 16:45 UTC, closed without merging