CYB-38
tp47/cybreach pull request #19
Opened 2023-11-29 12:52 UTC by gpologov

### Какую задачу решаем
https://linear.app/cybreach/issue/CYB-38/dobavit-service-workers

2023-11-29 15:51 UTC, tp47 requested changes

2023-11-29 15:51 UTC, tp47 commented on packages/client/src/main.tsx
> +function startServiceWorker() {
В `src/main.tsx` должна быть только инициализирующая логика
Вынеси, пожалуйста, `startServiceWorker` в отдельный файл в `src/services`

2023-11-29 15:51 UTC, tp47 commented on packages/client/sw.js
Не понятно, что значит "sw.js"
Переименуй, пожалуйста, в понятное название, например "cacheWorker.js"

2023-11-30 17:21 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечания
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-11-30 17:21 UTC, IvanPeleshok commented on packages/client/serviceWorkerConfig.js
> +        console.log('Opened cache')
Точно ли нужны отладочные инструменты в деве?

2023-11-30 17:21 UTC, IvanPeleshok commented on packages/client/src/services/serviceWorker/serviceWorker.ts
> +          console.log('ServiceWorker registration successful with scope: ', registration.scope)
Аналогично

2023-12-06 15:51 UTC, merged