CYB-31 : Ready for review
tp47/cybreach pull request #21
Opened 2023-11-30 12:55 UTC by mrzenxxx

Задача: 
https://linear.app/cybreach/issue/CYB-31/realizovat-sostoyanie-%C2%ABnachalo%C2%BB-i-sostoyanie-%C2%ABzavershenie-igry%C2%BB

2023-11-30 15:52 UTC, tp47 requested changes

2023-12-01 13:12 UTC, DazzlingFame approved these changes
Привет, отличная работа! Критичных правок нет, реквест принимаю.

2023-12-01 13:12 UTC, DazzlingFame commented on packages/client/src/components/organisms/EndGameScreen/EndGameScreen.tsx
> +type EndGameScreenProps = {
_Не обязательно к исправлению_

Иногда можно не указывать дополнительно пояснение к пропсу в его названии, например, если это единственный тип пропсов в единственном компоненте в файле.

В таких случаях достаточно просто писать
`type Props = {...}`

2023-12-01 13:12 UTC, DazzlingFame commented on packages/client/src/components/organisms/EndGameScreen/EndGameScreen.tsx
> +export default function EndGameScreen({ onStartGame, onLeaveGame, result }: EndGameScreenProps) {
_Не обязательно к исправлению_


Хорошим тоном считается типизировать реакт компонент через `React.FC`
Явное указание React.FC помогает точно контролировать, что функция возвращает корректное значение

Например:
`export const EndGameScreen: React.FC<Props> = ({onStartGame, onLeaveGame, result}) => {...}`

2023-12-01 13:47 UTC, merged