CYB-47, configure docker
tp47/cybreach pull request #40
Opened 2024-01-12 18:02 UTC by tp47

### Какую задачу решаем
https://linear.app/cybreach/issue/CYB-47/nastroit-servernuyu-infrastrukturu-dlya-foruma-emodzi-i-temizacii

2024-01-12 18:08 UTC, Memento-mo approved these changes

2024-01-12 19:37 UTC, Olegas requested changes
Добрый день.
Не очень понимаю что и зачем сделано.
У вас два compose-файла, один видимо для продакшена, другой для разработки. Отличаются они тем, что в файле для разработки есть pgadmin.
При этом по команде docker:dev указывается оба файла. А файл c сервером Dockerfile.server вообще никак не используется и не упоминается.
Я ожидал увидеть в docker-compose.yml его использование, но эти строки были удалены.

2024-01-13 15:31 UTC, Olegas commented on package.json
> +    "docker:dev": "docker-compose up -d && yarn dev"
А чем теперь отличается docker и docker:dev? Ведь они запускают один и тот же compose а значит будет запущен и postgres (хорошо) и server (что странно т.к. yarn dev запустит еще одну копию).
Как теперь это задумано работать?
К продакшен конфигу вопросов нет

2024-01-14 05:47 UTC, tp47 commented on package.json
> +    "docker:dev": "docker-compose up -d && yarn dev"
Уже несколько часов задание на проверке
Вы можете принять задание или отклонить?
Сколько можно тянуть?
![Screenshot_20240114_084543](https://github.com/tp47/cybreach/assets/116389510/42883b62-805c-4964-9366-7a055bf0933b)

2024-01-14 08:46 UTC, Olegas commented
Так я же задал вопрос в комментарии. От ответа на него зависит принять или вернуть на доработку.14 янв. 2024 г., в 08:47, tp47 ***@***.***> написал(а):﻿
@tp47 commented on this pull request.



In package.json:
> @@ -10,7 +10,9 @@
     "test": "lerna run test",
     "lint": "lerna run lint",
     "format": "lerna run format",
-    "preview": "lerna run preview"
+    "preview": "lerna run preview",
+    "docker": "docker-compose up --build",
+    "docker:dev": "docker-compose up -d && yarn dev"

Уже несколько часов задание на проверке
Вы можете принять задание или отклонить?
Сколько можно тянуть?
Screenshot_20240114_084543.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-01-14 10:15 UTC, tp47 commented
> Так я же задал вопрос в комментарии. От ответа на него зависит принять или вернуть на доработку.14 янв. 2024 г., в 08:47, tp47 ***@***.***> написал(а):﻿ @tp47 commented on this pull request. In package.json:
> @@ -10,7 +10,9 @@
> "test": "lerna run test", "lint": "lerna run lint", "format": "lerna run format", - "preview": "lerna run preview" + "preview": "lerna run preview", + "docker": "docker-compose up --build", + "docker:dev": "docker-compose up -d && yarn dev" Уже несколько часов задание на проверке Вы можете принять задание или отклонить? Сколько можно тянуть? Screenshot_20240114_084543.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Вы первый ревьюер за 8 спринтов, который ожидал ответа на вопрос
Ранее все ревьюеры или принимали, или отклоняли, задание сразу после проверки
Отвечать на вопросы в комментариях не требовалось
Понимаю, что вы желаете помочь и ценю ваш вклад и вашу работу
Я бы с удовольствием отвечал на вопросы, если бы у меня было достаточно времени
Но, к сожалению, до жесткого дедлайна оставались сутки, с момента последней отправки задания на проверку
Поэтому для меня главная цель - как можно скорее закрыть спринт
Вы же своим действием ввели меня в неопределенность, отняли время и нервы, чем я очень недоволен
Изходя из вышенаписанного, прошу как можно скорее или принимать, или отклонять задание
Что, предполагаю, поможет и вам, и мне

2024-01-14 14:39 UTC, Olegas approved these changes
Спасибо, работа принята

2024-01-16 07:30 UTC, merged