Add validation on LoginForm
tp47/cybreach pull request #9
Opened 2023-11-15 21:12 UTC by Kaitag7

Задача по валидации форм.
https://linear.app/kataevas/issue/CYB-18/dobavit-validaciyu-na-vse-formy

2023-11-15 21:20 UTC, Kaitag7 commented
Пришлось убрать компоненты с полями и прописать теги внутри LoginForm, так как методы формы ломались при прокидывании. 
Еще немного поменял структуру, так как заголовок и кнопку перехода на регистрацию нелогично держать внутри form, в form должны содержаться только поля с данными, которые отправляем на бэк и собственно сама кнопка отправки, остальное снаружи

2023-11-16 07:28 UTC, mrzenxxx commented
> Пришлось убрать компоненты с полями и прописать теги внутри LoginForm, так как методы формы ломались при прокидывании. 

Такое изменение делает фактически бессмысленным использование компонентной структуры, уверен, что можно найти решение с передачей методов,  предлагаю вместе подумать над этим и обратиться с вопросом к наставнику. 
В текущем виде тебе приходится дублировать стили на каждый элемент формы и это не правильно с точки зрения организации кода и дальнейшей поддержки.

> Еще немного поменял структуру, так как заголовок и кнопку перехода на регистрацию нелогично Юдержать внутри form, в form должны содержаться только поля с данными, которые отправляем на бэк и собственно сама кнопка отправки, остальное снаружи

Что здесь вкладываешь в понятие "логично" ? 

Вот две формы для примера. В одной разделение логично  - с точки зрения UI, во второй-нет, соответственно и реализована вёрстка, более того у Яндекса вообще все кнопки которые присутствуют на форме, вложены в её тег.
<img width="467" alt="Снимок экрана 2023-11-16 в 10 15 51" src="https://github.com/tp47/cybreach/assets/44780361/ed3966a7-bca8-4a89-bcf5-c8f28f5bcfb9">
<img width="387" alt="Снимок экрана 2023-11-16 в 10 16 23" src="https://github.com/tp47/cybreach/assets/44780361/3791ae2c-775e-4000-988f-405ec570bb58">


Максимум неудобств, которые доставляет вторая кнопка в форме - это то, что придётся в обработчике написать лишний event.preventDefault() и всё.

2023-11-16 07:40 UTC, tp47 commented
В документации описано, как подключить `register` к уже реализованным компонентам
Для этого нужно добавить prop `register` и передавать его в управляемый элемент
https://react-hook-form.com/get-started#Integratinganexistingform

2023-11-16 08:33 UTC, Kaitag7 commented
Дело не в неудобствах, а в том зачем нам использовать в теге form те элементы, которые в отправке формы никак не участвуют. Это я и подразумевал под словом "логично". 
В общем тут нет того, что ломает нам компонент, из-за чего надо обязательно юзать определенный вариант, но как мне показалось, элементы заголовка и второй кнопки лучше вынести за тег form.

2023-11-16 11:07 UTC, mrzenxxx approved these changes

2023-11-17 16:54 UTC, KataevAS requested changes

2023-11-17 16:54 UTC, KataevAS commented on packages/client/src/components/organisms/RegisterForm/RegisterForm.tsx
> +interface FormData {
Тут это выглядит логично, описаны поля, которые принимает сама форма.

2023-11-17 16:54 UTC, KataevAS commented on packages/client/src/components/organisms/patternsForm.tsx
> +export const namePattern = /^[А-ЯA-Z][а-яa-z-]*$/
Эти константы для регулярок не являются организмами. Нужно создать папку constants в /src и добавить туда файл, например, regular.ts и импортировать оттуда.

2023-11-17 18:04 UTC, KataevAS requested changes

2023-11-17 18:04 UTC, KataevAS commented on packages/client/src/types/formFields.ts
> +export interface FormFields {
Это не должно быть глобальным типом, т.к. сейчас мы создаем формы отдельными компонентами, а значит он должен быть внутри компонента конкретной формы и определять именно ее поля. А если использовать enum, то это будет выглядеть примерно так:
```typescript
interface LoginForm {
  [FieldsForm.EMAIL]: string,
  [FieldsForm.PASSWORD]: string
}
```

2023-11-17 20:20 UTC, Kaitag7 commented on packages/client/src/types/formFields.ts
> +export interface FormFields {
проблема в том, что register передаваемый в дочерние компоненты в этом случае выдает ошибку, что какие-то поля зарегистрированы, но не используются
register: UseFormRegister<FormFields> - поэтому и тип пропсов засунул общий formfields

и да попробовал вручную присвоить именно эти два интерфейса 
register: UseFormRegister<LoginForm | RegisterForm> - но ошибка никуда не делась

2023-11-17 20:46 UTC, KataevAS commented on packages/client/src/types/formFields.ts
> +export interface FormFields {
@Kaitag7 а что, если попробовать указать в компонентах, которые ожидают в пропсах register примерно так?
![image](https://github.com/tp47/cybreach/assets/38090158/118ab20f-ebb8-42b6-baec-543ca47123b3)

2023-11-17 21:19 UTC, Kaitag7 commented on packages/client/src/types/formFields.ts
> +export interface FormFields {
По типам сработало, спасибо за совет! Все поправил (если все комментария верно понял) и пушнул коммит.

2023-11-17 21:58 UTC, KataevAS requested changes

2023-11-17 21:58 UTC, KataevAS commented on packages/client/src/components/atoms/Input/Input.tsx
> +  autoComplete: string
type и autoComplete среди стандартных пропсов, потому их теперь не нужно дублировать внутри компонента, только если мы не хотим переопределить их, как обязательные

2023-11-17 21:58 UTC, KataevAS commented on packages/client/src/components/atoms/Input/Input.tsx
> +  const { handleInput, label, register, patternForm, type, autoComplete } = props
соответственно тут тоже

2023-11-17 21:58 UTC, KataevAS commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +enum LoginFields {
Только эти константы нужно импортировать из того enum FieldsForm, который ты ранее создал, например так:
![image](https://github.com/tp47/cybreach/assets/38090158/c46a4482-426c-4a38-b96a-94a4cf084f25)

Из-за типизации внутри хука, нужно передавать именно interface, а не type, потому экстендим

2023-11-17 21:58 UTC, KataevAS commented on packages/client/src/components/organisms/RegisterForm/RegisterForm.tsx
> +  } = useForm<Record<FieldsForm, string>>({ mode: 'onBlur' })
Тут ты импортировал типы, но нет гарантий, что все описанные поля там, нужны будут в этой форме, т.к. тот файл может пополняться, потому лучше выбрать именно нужные в этой форме, как в моем примере выше

2023-11-17 22:20 UTC, KataevAS commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +enum LoginFields {
Вот более верный способ типизации для компонент, вроде наших Field и Input

https://stackblitz.com/edit/reusable-rhf-ts-pt3?embed=1&file=src/components/molecules/form-input.tsx

Это позволит внутри формы определять какой конкретный тип будет лежать внутри каждого поля, что нужно, например, для чекбоксов

2023-11-17 22:22 UTC, KataevAS commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +enum LoginFields {
![image](https://github.com/tp47/cybreach/assets/38090158/273f7b8e-81a4-446c-a237-1e178c17c97a)
![image](https://github.com/tp47/cybreach/assets/38090158/82cb8c35-23d8-46d9-9bcb-ec520a9a0d66)
![image](https://github.com/tp47/cybreach/assets/38090158/390ebab2-5e93-4e45-a391-213a2c6f6170)

2023-11-17 22:28 UTC, KataevAS approved these changes

2023-11-18 13:27 UTC, KataevAS approved these changes

2023-11-18 19:51 UTC, KataevAS approved these changes

2023-11-18 20:29 UTC, IvanPeleshok commented on packages/client/src/components/organisms/LoginForm/LoginForm.tsx
> +              value: emailPattern,
Для валидации отлично подходят готовые решения, т.к они протестированы
К примеру, yup: https://medium.com/@msgold/creating-a-react-form-using-react-hook-form-and-yup-in-typescript-640168c5ed57#:~:text=Validating%20the%20Data%20with%20Yup

2023-11-18 20:30 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично постарались!

Оставил небольшой комментарий по улучшению валидации с помощью библиотеки  yup, предлагаю ознакомиться

Поздравляю, работа принята!

Хорошего дня :)

2023-11-19 13:58 UTC, merged